Feature/reditt
mrigorir/micro-reddit pull request #1
Opened 2021-05-05 21:37 UTC by francisuloko

Summary:

1. Created Comment, User and Post Model
2. Ran immigration to the DB
3. Add validation to user input
4. Establish the relationship between tables

2021-05-05 21:46 UTC, MahmoudBakr23 reviewed
## **Invalid Submission ⚠️**

Hello Team 👋🏻
I can see that you put a lot of work and effort into this project, but I'm afraid that I'm going to invalidate this PR due the following reasons

- Please make sure to set up the Linter properly and all its checks are passing.
- Kindly add a descriptive README file. 
- Add a proper PR headline.

Please make sure to do these changes in order to make the PR professional and get the code reviewed 😊
Good luck and happy coding 👍🏻

2021-05-06 00:51 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The models have been set up correctly.
    2. The linter checks pass as expected.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Add a more descriptive project description to the readme file

- [ ] The getting started section is missing a few important code examples. 
- Include `bundle install` to install all your project dependencies.
- Also add the `rails db:migrate` command.
- And finally `rails c` to interact with your terminal app. 😄 

- [ ] Check in-line comments for other sections

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-05-06 00:56 UTC, mke2111 commented on app/models/post.rb
> +  validates :user_id, presence: { message: 'This is needed to stabilish a relation with user table' }
- [ ] You do not need this field since it is taken care of by the associations set between the various tables. Remove this validation.
- Once a user signs in and creates a post, their user_id is added automatically since a Post belongs to a user and on the other hand a user has many posts that they can create.

2021-05-06 00:57 UTC, mke2111 commented on app/models/comment.rb
> +  validates :post_id, presence: { message: 'This is needed to stabilish a relation with post table' }
Remove the validations for `user_id` and `post_id` for the same reason as explained before.

2021-05-06 01:30 UTC, george-shammar approved these changes
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

**Good job guys. Thank you for implementing the changes from the previous review**. :clap: :clap: 

**This project is approved.** :+1: 

**You may go ahead and merge this branch.**

**Cheers!** :+1:

2021-05-06 01:31 UTC, merged